library/urls.py
from django.conf.urls import url

from . import views

app_name = 'library'
urlpatterns = [
    # ex: /library/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /library/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /library/category/toolkit/
    url(r'^category/(?P<bundle_type>[A-Za-z0-9_]+)/$', views.CategoryListView.as_view(), name='category'),
]

shareshot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect


urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('library/')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'library.views.login'),
    # url(r'^home/$', 'library.views.home'),
    url(r'^login/$', 'library.views.login'),
    url(r'^logout/$', 'library.views.logout'),

    url(r'^library/', include('library.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url('', include('social.apps.django_app.urls', namespace='social')),

]

library/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.views import generic

from django.contrib.auth import logout as auth_logout
# from django.contrib.auth.decorators import login_required

import logging
from .models import Bundle, BundleType

import base64
import markdown2
from library.models import Release

def login(request):
    # context = RequestContext(request, {
    #     'request': request, 'user': request.user})
    # return render_to_response('login.html', context_instance=context)
    if not request.user.is_anonymous():
        return HttpResponseRedirect("/")

    return render(request, 'login.html')

# @login_required(login_url='/')
# def home(request):
#     return render_to_response('index.html')

def logout(request):
    auth_logout(request)
    return redirect('/')

class IndexView(generic.ListView):
    template_name = 'library/index.html'
    context_object_name = 'bundle_list'

    def get_queryset(self):
        """Return the last five updated bundles."""
        return Bundle.objects.order_by('-last_modified')[:15]


class DetailView(generic.DetailView):
    model = Bundle
    template_name = 'library/detail.html'

    def get_releases(self):
        release_list = Release.objects.filter(bundle=self.object).order_by('-date', '-version')
        return release_list

    def get_labels(self):
        label_list = self.object.tags.split(",")
        return label_list

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['readme_html'] = markdown2.markdown(base64.b64decode(self.object.readme))
        context['release_list'] = self.get_releases()
        context['label_list'] = self.get_labels()
        return context


class CategoryListView(generic.ListView):
    template_name = 'library/index.html'
    context_object_name = 'bundle_list'

    # category = get_object_or_404(BundleType, pk=self.kwargs['bundle_type_id'])
    def get_queryset(self):
        """Return all bundles for the category."""
        self.category = get_object_or_404(BundleType, name=self.kwargs['bundle_type'])
        return Bundle.objects.filter(category=self.category).order_by('-last_modified')

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['category'] = self.category.name
        return context


def bundle_type_list(request, bundle_type_id):
    response = "Library list by bundle type %s."
    return HttpResponse(response % bundle_type_id)

library/templates/library/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>shareshot - helping the Shotgun community own their pipelines</title>
        <!-- Latest compiled and minified CSS -->
<!--         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="{% static 'css/bootstrap-slate.css' %}">

        <!-- Optional theme -->
<!--         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
 -->
        <!-- Latest compiled and minified JavaScript -->
        <!-- jQuery required by bootstrap -->
        <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <link href='https://fonts.googleapis.com/css?family=Rajdhani:400,300,500,600,700' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Palanquin+Dark:400,500,600,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/library.css' %}">
<!--         <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
 -->        <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

</head>
<body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <img alt="SG" src="{% static 'images/login_circle_logo@2x.png' %}">
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/">Code Library <span class="sr-only">(current)</span></a></li>
            <li class="dropdown">
              <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/library/category/toolkit/">Toolkit</a></li>
                <li><a href="/library/category/shotgun_api/">Shotgun API</a></li>
                <li><a href="/library/category/shotgun_events/">Shotgun Event Triggers</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="/library/">Latest</a></li>
              </ul>
            </li>
            <li><a href="#">About</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>
            <li><a href="#">Help</a></li>
            {% if user and not user.is_anonymous %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Your Profile</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout">Sign Out</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="/login">Login</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="content container">
<!--         <div class="row">
            <div class="col-md-12"> -->
            {% block content %}
            {% endblock %}
<!--             </div>
        </div> -->
    </div>
</body>
</html>

library/templates/library/category.html
<h2> Category </h2>
{% if category_list %}
    <ul>
    {% for bundle in category_list %}
        <li><a href="{% url 'library:detail' bundle.id %}">{{ bundle.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bundles are available.</p>
{% endif %}

<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>

library/templates/library/detail.html
{% extends 'library/base.html' %}
{% load ratings %}

{% block content %}

<div class="col-md-8">
    <h1>{{ bundle.name }}</h1>
    <p>
        <!-- s=60 sets the size to 60px | if using a generated github avatar, this has no effect -->
        <img src="{{ bundle.author_avatar_url }}&s=60" alt="{{ bundle.authors }}" class="img-circle author-avatar-url">
        By <a href="https://github.com/{{ bundle.authors }}">{{ bundle.authors }}</a></p>
    <p>{{ bundle.description }}</p>
    {% for label in label_list %}
        <button type="button" class="btn btn-info btn-xs">{{ label }}</button>
    {% endfor %}
    <p>&nbsp;</p>
    <h4 class="category">Category: {{ bundle.category }}</h4>


    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

    <h4 class="category">Homepage:
        {% if bundle.homepage %}
            <a href="{{ bundle.homepage }}">{{ bundle.homepage }}</a>
        {% else %}
            <a href="{{ bundle.source_url }}">{{ bundle.source_url }}</a>
        {% endif %}
    </h4>
    <p>&nbsp;</p>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Readme</h3>
        </div>
        <div class="panel-body">
            {{ readme_html|safe }}
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Releases</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover ">
              <tbody>

                {% for release in release_list %}
                    <tr>
                      <td><a href="{{ release.url }}">{{ release.version }}</a></td>
                      <td>{{ release.date|date }}</td>
                      <td>
                        {% if release.download_url %}
                            <a href="{{ release.download_url }}" class="btn btn-default btn-xs download-button" role="button">Download (.zip)</a>
                        {% endif %}
                      </td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>

        </div>
    </div>

    <ul class="list-group">
      <li class="list-group-item">
        <span class="badge">{{ bundle.stars }}</span>
        Stars
      </li>
      <li class="list-group-item">
        <span class="badge">{{ bundle.forks }}</span>
        Forks
      </li>
      <li class="list-group-item">
        <span class="badge">{{ bundle.last_modified|date }}</span>
        Last Modified
      </li>
      <li class="list-group-item">
        <span class="badge">{{ bundle.last_seen|date }}</span>
        Last Seen
      </li>
    </ul>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Ratings</h3>
        </div>
        <div class="panel-body">
            {% ratings object %}
        </div>
    </div>
</div>
    <!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
{% endblock %}

library/templates/library/index.html
{% extends 'library/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="jumbotron homeheader">
  <h1>tk-maya-playblast</h1>
  <p>A simple playblast app for Maya with some configurable settings.</p>
  <p><a href="/library/19/" class="btn btn-primary btn-lg">Learn more</a></p>
</div>

<div class="col-md-8">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Latest Contributions</h3>
        </div>
            {% if bundle_list %}
                    <div class="list-group">

                {% for bundle in bundle_list %}
                    <a href="{% url 'library:detail' bundle.id %}" class="list-group-item">
                        <div class="pull-right">
                            <p class="text-muted">{{ bundle.last_modified|date }}</p>
                        </div>
                            <h4 class="list-group-item-heading">
                                <img src="{{ bundle.author_avatar_url }}&s=30" alt="{{ bundle.authors }}" class="img-circle author-avatar-url-sml">
                                {{ bundle.name }}
                            </h4>
                            <p class="list-group-item-text"><span class="label label-primary">{{ bundle.category }}</span> {{ bundle.description }}</p>
                        <div class="clearfix"></div>
                    </a>
                {% endfor %}
                    </div>
            {% else %}
                <p>No bundles are available.</p>
            {% endif %}
    </div>
</div>

<div class="col-md-4">

    <div class="panel panel-info">    
        <div class="panel-heading">
            <h3 class="panel-title">Categories</h3>
        </div>
        <div class="list-group">
          <a href="/library/category/toolkit/" class="list-group-item">
            Toolkit
          </a>
          <a href="/library/category/shotgun_api/" class="list-group-item">
            Shotgun API
          </a>
          <a href="/library/category/shotgun_events/" class="list-group-item">
            Shotgun Event Triggers
          </a>
        </div>
    </div>
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3 class="panel-title">Library Stats</h3>
        </div>

            <ul class="list-group">
              <li class="list-group-item">
                <span class="badge">43</span>
                Projects
              </li>
              <li class="list-group-item">
                <span class="badge">197</span>
                Releases
              </li>
              <li class="list-group-item">
                <span class="badge">1332</span>
                Downloads
              </li>
              <li class="list-group-item">
                <span class="badge">Today at 09:35am PDT</span>
                Latest Update
              </li>
            </ul>

    </div>
</div>
{% endblock %}